spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_wa_elder?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password:

  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      file-size-threshold: 2KB
      max-request-size: 512MB

server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

system:
  store:
#    file-path: /Users/tomax/work/project/wa-elder/sources/files
#    video-path: /Users/tomax/work/project/wa-elder/sources/videos
    video-path: C:/mydata/wa-elder/sources/videos
